version: '3'

services:
  agentx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
      - PORT=9090
    volumes:
      - ./app:/app
    restart: unless-stopped
